import { appBarHeight } from "~/utils";
import type { AppsData } from "~/types";

const apps: AppsData[] = [
  // {
  //   id: "launchpad",
  //   title: "Launchpad",
  //   desktop: false,
  //   img: "img/icons/launchpad.png"
  // },
  // {
  //   id: "bear",
  //   title: "Bear",
  //   desktop: true,
  //   width: 860,
  //   height: 500,
  //   show: true,
  //   y: -40,
  //   img: "img/icons/bear.png",
  //   content: <Bear />
  // },
  // {
  //   id: "typora",
  //   title: "Typora",
  //   desktop: true,
  //   width: 600,
  //   height: 500,
  //   y: -40,
  //   img: "img/icons/typora.png",
  //   content: <Typora />
  // },
  // {
  //   id: "safari",
  //   title: "Safari",
  //   desktop: true,
  //   width: 860,
  //   minWidth: 375,
  //   minHeight: 465,
  //   x: 0,
  //   y: -90,
  //   img: "img/icons/safari.png",
  //   content: <Safari />
  // },
  {
    id: "Chrome",
    title: "Chrome",
    desktop: true,
    img: "img/icons/chrome.png",
    width: 860,
    height: 600,
    y: -40,
    content: <Chrome />,
    size: "213 MB",
    version: "128.0.6613.120",
    created: new Date('2008-09-02'),
    modified: new Date('2024-09-07'),
  },
  {
    id: "vscode",
    title: "VSCode",
    desktop: true,
    width: 900,
    height: 600,
    x: 0,
    y: -40,
    img: "img/icons/vscode.png",
    content: <VSCode />,
    size: "600 MB",
    version: "1.82.0",
    created: new Date('2015-04-29'), 
    modified: new Date('2024-09-06'),
  },  
  {
    id: "terminal",
    title: "Terminal",
    desktop: true,
    img: "img/icons/terminal.png",
    content: <Terminal />,
    size: "1.5 MB",
    version: "14.0",
    created: new Date('2001-03-24'), 
    modified: new Date('2023-09-26'),
  },  
  {
    id: "Gedit",
    title: "Contact",
    desktop: true,
    img: "img/icons/mail.png",
    width: 860,
    height: 500,
    y: -40,
    content: <Gedit />,
    size: "15 MB",
    version: "14.0",
    created: new Date('2001-03-24'),
    modified: new Date('2023-09-26'),
  },
  {
    id: "calculator",
    title: "Calculator",
    desktop: true,
    img: "img/icons/calculator.png",
    width: 500 * 0.65,
    height: 450 + appBarHeight,
    minWidth: 500 * 0.65,
    minHeight: 450 + appBarHeight,
    aspectRatio: 0.65,
    x: 0,
    y: -40,
    content: <Calculator />,
    size: "1.5 MB",
    version: "14.0",
    created: new Date('1984-01-01'),
    modified: new Date('2023-09-26'),
  },  
  {
    id: "AboutRaj",
    title: "AboutRaj",
    desktop: true,
    img: "img/icons/profile.png",
    width: 860,
    height: 500,
    y: -40,
    content: <AboutRaj />,
    size: "20 MB",
    created: new Date('2024-08-05'), 
    modified: new Date('2024-09-07'),
  },
  {
    id: "TradingView",
    title: "Trading View",
    desktop: true,
    img: "img/icons/tradingview.png",
    width: 860,
    height: 500,
    y: -40,
    content: <TradingView />,
    size: "244 MB",
    version: "2.4.0",
    created: new Date('2020-12-01'),
    modified: new Date('2023-06-14'),
  },  
  {
    id: "Music",
    title: "Music Player",
    desktop: true,
    img: "img/icons/music-player.png",
    width: 860,
    height: 600,
    y: -40,
    content: <Music />,
    size: "235 MB",
    version: "14.0",
    created: new Date('2019-10-07'),
    modified: new Date('2023-09-26'),
  },  
  {
    id: "Paint",
    title: "Paint",
    desktop: true,
    img: "img/icons/paint.png",
    width: 860,
    height: 600,
    y: -40,
    content: <Paint />,
    size: "156 MB",
    version: "2.6.0",
    created: new Date('2007-01-01'),
    modified: new Date('2022-03-01'),
  },  
  {
    id: "DevToys",
    title: "DevToys",
    desktop: true,
    img: "img/icons/code.png",
    width: 1000,
    height: 600,
    y: -40,
    content: <DevToys />,
    size: "250 MB",
    version: "2.0",
    created: new Date('2022-01-01'), 
    modified: new Date('2024-06-15'),
  },  
  {
    id: "Algo",
    title: "Algorithm Visualizer",
    desktop: true,
    img: "img/icons/algorithm.png",
    width: 860,
    height: 600,
    y: -40,
    content: <Algo />,
    size: "200 MB",
    version: "1.5",
    created: new Date('2023-01-01'), 
    modified: new Date('2023-07-15'),
  },
  {
    id: "Editor",
    title: "Quill",
    desktop: true,
    img: "img/icons/quill.png",
    width: 1000,
    height: 600,
    y: -40,
    content: <Editor />,
    size: "106.6 MB",
    version: "0.17.1",
    created: new Date('2017-01-01'), 
    modified: new Date('2023-10-28'),
  }
];

export default apps;
